import React, { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, FlatList, Linking, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useFocusEffect, useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { Button, Chip, ErrorModal, Header, Input } from "@/src/components/UI";
import { ApiError } from "@/src/api/client";
import { listInventory, listInventoryTransactions, listLowStock, type InventoryRow, type InventoryTransaction } from "@/src/api/endpoints";
import { colors, font, radii, spacing } from "@/src/theme";

export default function AdminInventory() {
  const router = useRouter();
  const [rows, setRows] = useState<InventoryRow[]>([]);
  const [transactions, setTransactions] = useState<InventoryTransaction[]>([]);
  const [view, setView] = useState<"stock" | "low" | "moves">("stock");
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { const [stock, low, moves] = await Promise.all([listInventory(), listLowStock(), listInventoryTransactions()]); setRows(stock || []); setTransactions(moves || []); setLow(low || []); } catch (e) { setError(e instanceof ApiError ? e.message : "Failed to load inventory"); } }, []);
  const [low, setLow] = useState<InventoryRow[]>([]);
  useEffect(() => { setLoading(true); load().finally(() => setLoading(false)); }, [load]);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const filteredRows = useMemo(() => (view === "low" ? low : rows).filter((row) => `${row.name} ${row.productCode || ""} ${row.category || ""} ${row.brand || ""}`.toLowerCase().includes(search.trim().toLowerCase())), [low, rows, search, view]);
  async function exportCsv() { const csv = ["productCode,name,category,brand,stock,reorderLevel,unitCost,valuation,rack", ...rows.map((row) => [row.productCode, row.name, row.category, row.brand, row.stock, row.reorderLevel, row.unitCost, row.valuation, `${row.rackName || ""} ${row.rackSlot || ""}`].map((value) => `"${String(value || "").replace(/"/g, '""')}"`).join(","))].join("\n"); try { await Linking.openURL(`data:text/csv;charset=utf-8,${encodeURIComponent(csv)}`); } catch { setError("Could not open inventory export."); } }
  return <SafeAreaView style={styles.safe} edges={["top", "bottom"]}><Header title="Stock & Inventory" subtitle={`${rows.length} products`} onBack={() => router.back()} right={<TouchableOpacity testID="export-inventory" onPress={exportCsv} hitSlop={8}><Ionicons name="download-outline" size={23} color={colors.primary} /></TouchableOpacity>} /><View style={styles.controls}><Input testID="inventory-search" value={search} onChangeText={setSearch} placeholder="Search product, code, category, or brand" style={styles.search} /><View style={styles.tabs}><Chip label="Current stock" selected={view === "stock"} onPress={() => setView("stock")} testID="inventory-stock-tab" /><Chip label="Low stock" selected={view === "low"} onPress={() => setView("low")} testID="inventory-low-tab" /><Chip label="Stock in/out" selected={view === "moves"} onPress={() => setView("moves")} testID="inventory-moves-tab" /></View></View>{loading ? <View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /></View> : view === "moves" ? <FlatList data={transactions.filter((item) => `${item.productName} ${item.productCode}`.toLowerCase().includes(search.toLowerCase()))} keyExtractor={(item, index) => `${item.referenceId}-${index}`} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={styles.empty}>No stock movements.</Text>} renderItem={({ item }) => <View style={styles.row}><View style={styles.main}><Text style={styles.name}>{item.productName}</Text><Text style={styles.meta}>{item.productCode} · {new Date(item.at).toLocaleString()}</Text></View><Text style={[styles.movement, { color: item.type === "in" ? colors.success : colors.error }]}>{item.type === "in" ? "+" : "-"}{item.quantity}</Text></View>} /> : <FlatList data={filteredRows} keyExtractor={(item) => item.productId} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={styles.empty}>No inventory records.</Text>} renderItem={({ item }) => <View style={styles.row} testID={`inventory-${item.productId}`}><View style={styles.main}><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.productCode || "Legacy product"} · {item.category || ""}</Text><Text style={styles.meta}>{item.rackName ? `${item.rackName} / ${item.rackSlot}` : "No rack location"}</Text></View><View style={styles.right}><Text style={[styles.stock, item.stock <= item.reorderLevel && styles.alert]}>{item.stock}</Text><Text style={styles.meta}>value ₹{item.valuation}</Text></View></View>} />}<ErrorModal visible={!!error} message={error || ""} onClose={() => setError(null)} /></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.bg }, controls: { paddingHorizontal: spacing.lg, paddingTop: spacing.md }, search: { marginBottom: spacing.sm }, tabs: { flexDirection: "row", gap: spacing.sm, marginBottom: spacing.sm }, center: { flex: 1, alignItems: "center", justifyContent: "center" }, list: { padding: spacing.lg, paddingTop: spacing.sm, paddingBottom: 40 }, row: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radii.md, padding: spacing.md, marginBottom: spacing.sm, flexDirection: "row", alignItems: "center", gap: spacing.sm }, main: { flex: 1 }, right: { alignItems: "flex-end" }, name: { ...font.title, color: colors.textPrimary }, meta: { color: colors.textSecondary, fontSize: 12, marginTop: 3 }, stock: { fontSize: 20, fontWeight: "800", color: colors.textPrimary }, alert: { color: colors.error }, movement: { fontSize: 18, fontWeight: "800" }, empty: { textAlign: "center", color: colors.textSecondary, padding: spacing.xl } });
