import React, { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, FlatList, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useFocusEffect, useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { AppModal, Button, Chip, ErrorModal, Header, Input } from "@/src/components/UI";
import { ApiError } from "@/src/api/client";
import { getPartnerRewards, listPartners, reviewPartnerKyc, type Partner, type RewardWallet } from "@/src/api/endpoints";
import { colors, font, radii, spacing } from "@/src/theme";

export default function AdminPartners() {
  const router = useRouter();
  const [partners, setPartners] = useState<Partner[]>([]);
  const [filter, setFilter] = useState("all");
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState<Partner | null>(null);
  const [wallet, setWallet] = useState<RewardWallet | null>(null);
  const [saving, setSaving] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setPartners((await listPartners({ search, kyc_status: filter === "all" ? undefined : filter })) || []); } catch (e) { setError(e instanceof ApiError ? e.message : "Failed to load partners"); } }, [filter, search]);
  useEffect(() => { setLoading(true); load().finally(() => setLoading(false)); }, [load]);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const tabs = useMemo(() => ["all", "pending", "approved", "rejected"], []);
  async function openPartner(partner: Partner) { setSelected(partner); try { setWallet(await getPartnerRewards(partner.id)); } catch { setWallet(null); } }
  async function review(approved: boolean) { if (!selected) return; setSaving(true); try { const updated = await reviewPartnerKyc(selected.id, { approved, locationVerified: approved }); setSelected(updated); await load(); } catch (e) { setError(e instanceof ApiError ? e.message : "Could not review KYC"); } finally { setSaving(false); } }
  return <SafeAreaView style={styles.safe} edges={["top", "bottom"]}><Header title="Referral Partners" subtitle={`${partners.length} partner${partners.length === 1 ? "" : "s"}`} onBack={() => router.back()} /><View style={styles.controls}><Input testID="partner-search" value={search} onChangeText={setSearch} placeholder="Search name, phone, pincode, city, area, manager" style={styles.search} /><FlatList horizontal showsHorizontalScrollIndicator={false} data={tabs} keyExtractor={(item) => item} contentContainerStyle={styles.tabs} renderItem={({ item }) => <Chip label={item[0].toUpperCase() + item.slice(1)} selected={filter === item} onPress={() => setFilter(item)} testID={`partner-filter-${item}`} />} /></View>{loading ? <View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /></View> : <FlatList data={partners} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={styles.empty}>No partners found.</Text>} renderItem={({ item }) => <TouchableOpacity testID={`partner-row-${item.id}`} style={styles.row} onPress={() => openPartner(item)}><View style={styles.main}><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.businessName || "No business name"} · {item.city || item.area || "No location"}</Text><Text style={styles.meta}>{item.phone} · {item.salesManager || "Unassigned manager"}</Text></View><View style={[styles.status, item.kycStatus === "approved" ? styles.good : item.kycStatus === "rejected" ? styles.bad : styles.pending]}><Text style={styles.statusText}>{item.kycStatus}</Text></View></TouchableOpacity>} />}
    <AppModal testID="partner-details" visible={!!selected} onClose={() => setSelected(null)} title={selected?.name}><Text style={styles.meta}>Business: {selected?.businessName || "-"}</Text><Text style={styles.meta}>Location: {[selected?.area, selected?.city, selected?.pincode].filter(Boolean).join(", ") || "-"}</Text><Text style={styles.meta}>KYC: {selected?.kycStatus} · Documents: {selected?.documents?.length || 0}</Text><Text style={styles.balance}>Reward balance: {wallet?.balance ?? selected?.rewardBalance ?? 0}</Text>{selected?.kycStatus === "pending" && <View style={styles.actions}><Button testID="approve-partner-kyc" title="Approve KYC" onPress={() => review(true)} loading={saving} /><Button testID="reject-partner-kyc" title="Reject" variant="danger" onPress={() => review(false)} loading={saving} /></View>}<Text style={styles.historyTitle}>Reward passbook</Text>{wallet?.entries?.length ? wallet.entries.map((entry) => <Text key={entry.id} style={styles.history}>{entry.createdAt} · {entry.type} · {entry.points} points · RFQ {entry.quotationId.slice(0, 8)}</Text>) : <Text style={styles.meta}>No reward entries yet.</Text>}</AppModal><ErrorModal visible={!!error} message={error || ""} onClose={() => setError(null)} /></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.bg }, controls: { paddingHorizontal: spacing.lg, paddingTop: spacing.md }, search: { marginBottom: spacing.sm }, tabs: { gap: spacing.sm, paddingBottom: spacing.sm }, center: { flex: 1, alignItems: "center", justifyContent: "center" }, list: { padding: spacing.lg, paddingTop: spacing.sm }, row: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radii.md, padding: spacing.md, marginBottom: spacing.sm, flexDirection: "row", alignItems: "center", gap: spacing.sm }, main: { flex: 1 }, name: { ...font.title, color: colors.textPrimary }, meta: { color: colors.textSecondary, fontSize: 12, marginTop: 4 }, status: { borderRadius: radii.pill, paddingHorizontal: 8, paddingVertical: 5 }, good: { backgroundColor: colors.successBg }, bad: { backgroundColor: colors.errorBg }, pending: { backgroundColor: colors.warningBg }, statusText: { color: colors.textPrimary, fontSize: 11, fontWeight: "700" }, empty: { textAlign: "center", color: colors.textSecondary, padding: spacing.xl }, balance: { color: colors.primary, fontSize: 20, fontWeight: "800", marginTop: spacing.lg }, actions: { flexDirection: "row", gap: spacing.sm, marginTop: spacing.md }, historyTitle: { ...font.title, color: colors.textPrimary, marginTop: spacing.lg, marginBottom: spacing.sm }, history: { color: colors.textSecondary, fontSize: 11, marginBottom: 5 } });
