import React, { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, FlatList, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useFocusEffect, useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { AppModal, Button, Chip, ErrorModal, Header, Input } from "@/src/components/UI";
import { ApiError } from "@/src/api/client";
import { createTeamUser, listTeamUsers, updateTeamUser, type TeamUser } from "@/src/api/endpoints";
import { colors, font, radii, spacing } from "@/src/theme";

const roles: TeamUser["role"][] = ["admin", "store_manager", "staff"];
const roleLabels = { admin: "Admin", store_manager: "Store manager", staff: "Staff" };
export default function AdminTeam() {
  const router = useRouter();
  const [users, setUsers] = useState<TeamUser[]>([]);
  const [filter, setFilter] = useState<"all" | TeamUser["role"]>("all");
  const [query, setQuery] = useState("");
  const [editor, setEditor] = useState<TeamUser | null | undefined>(undefined);
  const [name, setName] = useState(""); const [contact, setContact] = useState(""); const [passcode, setPasscode] = useState(""); const [role, setRole] = useState<TeamUser["role"]>("staff");
  const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setUsers((await listTeamUsers()) || []); } catch (e) { setError(e instanceof ApiError ? e.message : "Failed to load team"); } }, []);
  useEffect(() => { setLoading(true); load().finally(() => setLoading(false)); }, [load]); useFocusEffect(useCallback(() => { load(); }, [load]));
  const filtered = useMemo(() => users.filter((user) => (filter === "all" || user.role === filter) && `${user.name} ${user.contactNumber}`.toLowerCase().includes(query.toLowerCase())), [filter, query, users]);
  function openCreate() { setEditor(null); setName(""); setContact(""); setPasscode(""); setRole("staff"); }
  function openEdit(user: TeamUser) { setEditor(user); setName(user.name); setContact(user.contactNumber); setRole(user.role); setPasscode(""); }
  async function save() { if (!name.trim() || !contact.trim() || (!editor && passcode.length < 4)) { setError("Name, contact, and a 4-character passcode are required."); return; } setSaving(true); try { if (editor) await updateTeamUser(editor.id, { name: name.trim(), contactNumber: contact.trim(), role, isActive: editor.isActive }); else await createTeamUser({ name: name.trim(), contactNumber: contact.trim(), role, passcode }); setEditor(undefined); await load(); } catch (e) { setError(e instanceof ApiError ? e.message : "Could not save team user"); } finally { setSaving(false); } }
  async function toggle(user: TeamUser) { try { await updateTeamUser(user.id, { name: user.name, contactNumber: user.contactNumber, role: user.role, isActive: !user.isActive }); await load(); } catch (e) { setError(e instanceof ApiError ? e.message : "Could not update status"); } }
  return <SafeAreaView style={styles.safe} edges={["top", "bottom"]}><Header title="Team Management" subtitle={`${filtered.length} of ${users.length} users`} onBack={() => router.back()} right={<TouchableOpacity testID="open-add-team-user" onPress={openCreate} hitSlop={8}><Ionicons name="add-circle" size={26} color={colors.primary} /></TouchableOpacity>} /><View style={styles.controls}><Input testID="team-search" value={query} onChangeText={setQuery} placeholder="Search team" style={styles.search} /><FlatList horizontal showsHorizontalScrollIndicator={false} data={["all", ...roles]} keyExtractor={(item) => item} contentContainerStyle={styles.chips} renderItem={({ item }) => <Chip label={item === "all" ? "All" : roleLabels[item as TeamUser["role"]]} selected={filter === item} onPress={() => setFilter(item as typeof filter)} testID={`team-filter-${item}`} />} /></View>{loading ? <View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /></View> : <FlatList data={filtered} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={styles.empty}>No team users found.</Text>} renderItem={({ item }) => <View style={styles.row} testID={`team-user-${item.id}`}><View style={styles.main}><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.contactNumber} · {roleLabels[item.role]}</Text><Text style={styles.permissions}>{(item.permissions || []).join(" · ") || "No permissions assigned"}</Text></View><TouchableOpacity testID={`toggle-team-${item.id}`} onPress={() => toggle(item)} hitSlop={8}><Ionicons name={item.isActive ? "checkmark-circle" : "close-circle"} size={22} color={item.isActive ? colors.success : colors.textMuted} /></TouchableOpacity><TouchableOpacity testID={`edit-team-${item.id}`} onPress={() => openEdit(item)} hitSlop={8} style={styles.icon}><Ionicons name="create-outline" size={19} color={colors.primary} /></TouchableOpacity></View>} />}
    <AppModal testID="team-user-editor" visible={editor !== undefined} onClose={() => setEditor(undefined)} title={editor ? "Edit team user" : "New team user"}><Input testID="team-name-input" label="Name" value={name} onChangeText={setName} placeholder="Full name" autoCapitalize="words" /><Input testID="team-contact-input" label="Contact number" value={contact} onChangeText={setContact} keyboardType="phone-pad" /><Text style={styles.label}>Role</Text><View style={styles.roleRow}>{roles.map((item) => <Chip key={item} label={roleLabels[item]} selected={role === item} onPress={() => setRole(item)} testID={`team-role-${item}`} />)}</View>{!editor && <Input testID="team-passcode-input" label="Passcode" value={passcode} onChangeText={setPasscode} secureTextEntry keyboardType="numeric" />}{editor && <Text style={styles.hint}>Role defaults: permissions are applied automatically for this account.</Text>}<Button testID="save-team-user" title={editor ? "Save changes" : "Create user"} onPress={save} loading={saving} fullWidth /></AppModal><ErrorModal visible={!!error} message={error || ""} onClose={() => setError(null)} /></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.bg }, controls: { paddingHorizontal: spacing.lg, paddingTop: spacing.md }, search: { marginBottom: spacing.sm }, chips: { gap: spacing.sm, paddingBottom: spacing.sm }, center: { flex: 1, alignItems: "center", justifyContent: "center" }, list: { padding: spacing.lg, paddingTop: spacing.sm }, row: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radii.md, padding: spacing.md, marginBottom: spacing.sm, flexDirection: "row", alignItems: "center", gap: spacing.sm }, main: { flex: 1 }, name: { ...font.title, color: colors.textPrimary }, meta: { color: colors.textSecondary, fontSize: 12, marginTop: 3 }, permissions: { color: colors.textMuted, fontSize: 11, marginTop: 4 }, icon: { padding: 4 }, empty: { textAlign: "center", color: colors.textSecondary, padding: spacing.xl }, label: { color: colors.textSecondary, fontWeight: "600", marginBottom: spacing.sm }, roleRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginBottom: spacing.md }, hint: { color: colors.textSecondary, fontSize: 12, marginBottom: spacing.md } });
